name: RUN NODE APP
on: 
  push:
    branches:
      - main
    paths:
      - "backend-apps/**"
env:
  IMAGE_TAG: "v2"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: backend-apps
        run: docker build -t pib21/nxz-node-app:${{ env.IMAGE_TAG }} .

      - name: Push into Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u pib21 --password-stdin
          docker push pib21/nxz-node-app:${{ env.IMAGE_TAG }}

  deployment:
    runs-on: self-hosted
    needs: build-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Init Terraform
        working-directory: infra-code
        run: terraform init

      - name: Clean Name Space
        run: kubectl delete namespace nxz-c-node-app --ignore-not-found=true

      - name: Apply Terraform
        working-directory: infra-code
        run: terraform apply -auto-approve -var="image=pib21/nxz-node-app:${{ env.IMAGE_TAG }}"
